"""add_gps_polyline_to_activities

Revision ID: 72559f36d496
Revises: f7a8b9c0d1e2
Create Date: 2026-02-03 13:09:20.115736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72559f36d496'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('target_intensity', sa.String(length=20), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('planned_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_activity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['completed_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_workouts_id'), 'planned_workouts', ['id'], unique=False)
    op.create_index(op.f('ix_planned_workouts_planned_date'), 'planned_workouts', ['planned_date'], unique=False)
    op.add_column('activities', sa.Column('gps_polyline', sa.JSON(), nullable=True))
    op.add_column('activities', sa.Column('gps_fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('computed_metrics', 'algorithm_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('computed_metrics', 'sport_specific',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_computed_metrics_algo_version', table_name='computed_metrics')
    op.alter_column('events', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_events_date', table_name='events')
    op.drop_index('ix_events_priority', table_name='events', postgresql_where="((priority)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying])::text[]))")
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('sync_jobs', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('sync_jobs', 'triggered_by',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_sync_jobs_started_at', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_status', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_triggered_by', table_name='sync_jobs')
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.alter_column('training_phases', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_phases_dates', table_name='training_phases')
    op.drop_index('ix_phases_event', table_name='training_phases')
    op.create_index(op.f('ix_training_phases_id'), 'training_phases', ['id'], unique=False)
    op.drop_constraint('training_phases_target_event_id_fkey', 'training_phases', type_='foreignkey')
    op.add_column('user_settings', sa.Column('hr_zones', sa.JSON(), nullable=True))
    op.alter_column('weekly_metrics', 'volume_by_discipline',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('weekly_metrics', 'intensity_distribution',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_weekly_metrics_date', table_name='weekly_metrics')
    op.create_index(op.f('ix_weekly_metrics_id'), 'weekly_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_metrics_id'), table_name='weekly_metrics')
    op.create_index('ix_weekly_metrics_date', 'weekly_metrics', ['week_start'], unique=False)
    op.alter_column('weekly_metrics', 'intensity_distribution',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weekly_metrics', 'volume_by_discipline',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('user_settings', 'hr_zones')
    op.create_foreign_key('training_phases_target_event_id_fkey', 'training_phases', 'events', ['target_event_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_training_phases_id'), table_name='training_phases')
    op.create_index('ix_phases_event', 'training_phases', ['target_event_id'], unique=False)
    op.create_index('ix_phases_dates', 'training_phases', ['start_date', 'end_date'], unique=False)
    op.alter_column('training_phases', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.create_index('ix_sync_jobs_triggered_by', 'sync_jobs', ['triggered_by'], unique=False)
    op.create_index('ix_sync_jobs_status', 'sync_jobs', ['status'], unique=False)
    op.create_index('ix_sync_jobs_started_at', 'sync_jobs', ['started_at'], unique=False)
    op.alter_column('sync_jobs', 'triggered_by',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('sync_jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.create_index('ix_events_priority', 'events', ['priority'], unique=False, postgresql_where="((priority)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying])::text[]))")
    op.create_index('ix_events_date', 'events', ['event_date'], unique=False)
    op.alter_column('events', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_computed_metrics_algo_version', 'computed_metrics', ['algorithm_version'], unique=False)
    op.alter_column('computed_metrics', 'sport_specific',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('computed_metrics', 'algorithm_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.drop_column('activities', 'gps_fetched_at')
    op.drop_column('activities', 'gps_polyline')
    op.drop_index(op.f('ix_planned_workouts_planned_date'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workouts_id'), table_name='planned_workouts')
    op.drop_table('planned_workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###
