"""add_activity_metrics_columns

Revision ID: 3bcb9f0b0776
Revises: 72559f36d496
Create Date: 2026-02-03 20:01:27.359772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcb9f0b0776'
down_revision = '72559f36d496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('avg_power', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('max_power', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('normalized_power', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_speed', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('max_speed', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_cadence', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('max_cadence', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('elevation_gain', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('elevation_loss', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('aerobic_te', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('anaerobic_te', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'anaerobic_te')
    op.drop_column('activities', 'aerobic_te')
    op.drop_column('activities', 'elevation_loss')
    op.drop_column('activities', 'elevation_gain')
    op.drop_column('activities', 'max_cadence')
    op.drop_column('activities', 'avg_cadence')
    op.drop_column('activities', 'max_speed')
    op.drop_column('activities', 'avg_speed')
    op.drop_column('activities', 'normalized_power')
    op.drop_column('activities', 'max_power')
    op.drop_column('activities', 'avg_power')
    # ### end Alembic commands ###
