"""initial

Revision ID: bd7d79f99083
Revises: 
Create Date: 2026-02-02 09:37:01.156003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7d79f99083'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('activity_name', sa.String(), nullable=True),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('intensity_zone', sa.String(), nullable=True),
    sa.Column('body_regions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('hr_zone_1_minutes', sa.Float(), nullable=True),
    sa.Column('hr_zone_2_minutes', sa.Float(), nullable=True),
    sa.Column('hr_zone_3_minutes', sa.Float(), nullable=True),
    sa.Column('hr_zone_4_minutes', sa.Float(), nullable=True),
    sa.Column('hr_zone_5_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_garmin_id'), 'activities', ['garmin_id'], unique=True)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('computed_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('readiness_factors', sa.JSON(), nullable=True),
    sa.Column('acute_load', sa.Float(), nullable=True),
    sa.Column('chronic_load', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('acwr_status', sa.String(), nullable=True),
    sa.Column('fatigue_upper', sa.Float(), nullable=True),
    sa.Column('fatigue_lower', sa.Float(), nullable=True),
    sa.Column('fatigue_cardio', sa.Float(), nullable=True),
    sa.Column('fatigue_cns', sa.Float(), nullable=True),
    sa.Column('weekly_volume_by_discipline', sa.JSON(), nullable=True),
    sa.Column('intensity_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_metrics_date'), 'computed_metrics', ['date'], unique=True)
    op.create_index(op.f('ix_computed_metrics_id'), 'computed_metrics', ['id'], unique=False)
    op.create_table('daily_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hrv_status', sa.Float(), nullable=True),
    sa.Column('hrv_7day_avg', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('resting_hr_7day_avg', sa.Float(), nullable=True),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('body_battery_morning', sa.Integer(), nullable=True),
    sa.Column('body_battery_evening', sa.Integer(), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('vo2max_running', sa.Float(), nullable=True),
    sa.Column('vo2max_cycling', sa.Float(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=True),
    sa.Column('training_load_7day', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_health_date'), 'daily_health', ['date'], unique=True)
    op.create_index(op.f('ix_daily_health_id'), 'daily_health', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('resting_hr_baseline', sa.Integer(), nullable=True),
    sa.Column('hrv_baseline', sa.Float(), nullable=True),
    sa.Column('sleep_target_hours', sa.Float(), nullable=True),
    sa.Column('disciplines_enabled', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('weekly_volume_targets', sa.JSON(), nullable=True),
    sa.Column('fatigue_decay_rates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_daily_health_id'), table_name='daily_health')
    op.drop_index(op.f('ix_daily_health_date'), table_name='daily_health')
    op.drop_table('daily_health')
    op.drop_index(op.f('ix_computed_metrics_id'), table_name='computed_metrics')
    op.drop_index(op.f('ix_computed_metrics_date'), table_name='computed_metrics')
    op.drop_table('computed_metrics')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_garmin_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
